### ISSUE TITLE
Clean up custom_pbsa_vic script

### ISSUE THREAD

**Issue by Kyeo1983** [Kyeo1983/pypeline#2]

**Comment by Kyeo1983** [comment]
@singulari, you have problems with accessing log files you said?

**Comment by singulari** [comment]
yep there is permission error
![1](https://user-images.githubusercontent.com/24800748/62829791-c5d5fc00-bc33-11e9-8d2b-117c8e587dd7.png)

**Comment by Kyeo1983** [comment]
Ok, looks like when @yuuuuu0801 ran her script, she dynamically created the log file under her name, and thus you can't write to it. I've updated the _sample_job.sh_ file and added some permission granting commands at bottom. For your .sh files, next time add the 3 new chmod lines like _sample_jobs.sh_. Basically, it is to just grant write-access to any log files that you may have created during run.

```
chmod 777 /home/kyeoses/pypeline/var/logs/luigi/luigi.log
chmod 777 /home/kyeoses/pypeline/var/logs/luigi/luigi-server.log
chmod 777 /home/kyeoses/pypeline/var/logs/luigi/luigi-stages.log
```

**Comment by singulari** [comment]
I see i can now run the script already. Thank you (:
